name: Build and deploy docs
# Run only if docs or mkdocs.yml changed
on:
  push:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: "Build MkDocs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: python -m pip install --upgrade poetry
      - name: Poetry install dependencies
        run: poetry install

      - run: poetry run mkdocs build
      - uses: actions/upload-artifact@v2
        with:
          name: site
          path: site/

  deploy:
    name: "Publish Docs"
    needs: build
    
    uses: bayer-int/actions-workflows/.github/workflows/publish-docs.yml@main
    with:
      artifact:   site
      dir:        site
      invalidate: true
      preview: ${{ github.ref != 'refs/heads/master' && github.run_id || '' }}
      namespace:  'crv'
